### ISSUE TITLE
make use of react-admin

### ISSUE THREAD

**Issue by zeusbaba** [navikt/dokumentfordeling-web#4]
so that we can leverage rich react components and also material-ui    
https://github.com/marmelab/react-admin

**Comment by zeusbaba** [comment]
let's re-evaluate this option...  
because this might introduce unnecessary complexity to proxycontroller.

**Comment by zeusbaba** [comment]
https://marmelab.com/react-admin/DataProviders.html  
creating a custom simplified data provider on the client side (react app) can also be another option.  
in any case, we should avoid any extreme changes in the spring boot app side.  
simplicity is essential.

**Comment by myhres** [comment]
Using material-ui for react will be a simpler and more fit option
